package com.streetbell.admin

import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Rect
import android.net.Uri
import android.graphics.Bitmap.CompressFormat
import androidx.exifinterface.media.ExifInterface
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.Image
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.window.Dialog
import coil.compose.AsyncImage
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.MultipartBody
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.Executors

private data class Employee(val id:String,val code:String,val name:String,val department:String?,val enrolled:Boolean,val active:Boolean,val photoUrl:String?)
private data class Attendance(val employee:String,val code:String,val status:String,val time:String,val device:String,val photo:String?)
private data class Device(val id:String,val name:String,val status:String,val code:String?,val assigned:Int)

class MainActivity:ComponentActivity(){
 private val http=OkHttpClient(); private val executor=Executors.newCachedThreadPool(); private val baseUrl="https://attendance-backend-rkny.onrender.com"; private var token:String?=null
 override fun onCreate(b:Bundle?){super.onCreate(b);token=getSharedPreferences("admin",0).getString("token",null);setContent{App()}}
 @Composable private fun App(){var logged by remember{mutableStateOf(token!=null)};if(!logged)Login{logged=true}else Dashboard{getSharedPreferences("admin",0).edit().remove("token").apply();token=null;logged=false}}
 @Composable private fun Login(ok:()->Unit){var email by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("ATTEND ADMIN",fontSize=30.sp);Spacer(Modifier.height(20.dp));OutlinedTextField(email,{email=it},label={Text("Email")},modifier=Modifier.fillMaxWidth());OutlinedTextField(pass,{pass=it},label={Text("Password")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(12.dp));Button({login(email,pass){s,m->msg=m;if(s)ok()}},modifier=Modifier.fillMaxWidth()){Text("LOGIN")};Text(msg)}}
 @Composable private fun Dashboard(logout:()->Unit){var tab by remember{mutableStateOf(0)};var refresh by remember{mutableStateOf(0)};var employees by remember{mutableStateOf(emptyList<Employee>())};var attendance by remember{mutableStateOf(emptyList<Attendance>())};var devices by remember{mutableStateOf(emptyList<Device>())};LaunchedEffect(refresh){loadEmployees{employees=it};loadAttendance{attendance=it};loadDevices{devices=it}};Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("ATTEND ADMIN",fontSize=25.sp);Row{TextButton({refresh++}){Text("SYNC")};TextButton(logout){Text("LOG OUT")}}};Spacer(Modifier.height(10.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("STAFF","ATTENDANCE","DEVICES").forEachIndexed{i,n->Button({tab=i},modifier=Modifier.weight(1f)){Text(n)}}};Spacer(Modifier.height(12.dp));when(tab){0->Staff(employees){refresh++};1->AttendanceList(attendance);2->DeviceList(devices,employees){refresh++}}}}
 @Composable private fun Staff(list:List<Employee>,reload:()->Unit){var show by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<Employee?>(null)};var preview by remember{mutableStateOf<Employee?>(null)};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Staff",fontSize=24.sp);Button({show=true}){Text("+ ADD EMPLOYEE")}};Text("${list.size} employees");LazyColumn{items(list){e->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)){if(!e.photoUrl.isNullOrBlank()){AsyncImage(model=e.photoUrl,contentDescription="${e.name} photo",contentScale=ContentScale.Crop,modifier=Modifier.size(72.dp))}else{Surface(Modifier.size(72.dp),tonalElevation=2.dp){Box(contentAlignment=Alignment.Center){Text("NO\nPHOTO",fontSize=11.sp)}}};Column(Modifier.weight(1f)){Text(e.name,fontSize=18.sp);Text("${e.code} • ${e.department.orEmpty()}");Text(if(e.enrolled)"Face: OK ✓"else"Face: NOT ENROLLED");Row(verticalAlignment=Alignment.CenterVertically){Text(if(e.photoUrl.isNullOrBlank())"PHOTO: NOT UPLOADED"else"PHOTO: OK ✓",fontSize=13.sp);if(!e.photoUrl.isNullOrBlank())Text("  •  CLOUDINARY",fontSize=11.sp)}}};Row(Modifier.fillMaxWidth().padding(horizontal=12.dp).padding(bottom=10.dp),horizontalArrangement=Arrangement.spacedBy(6.dp)){Button({edit=e}){Text(if(e.photoUrl.isNullOrBlank())"ADD PHOTO"else"CHANGE PHOTO")};if(!e.photoUrl.isNullOrBlank())OutlinedButton({preview=e}){Text("VIEW PHOTO")};Button({removeEmployee(e.id,reload)}){Text("REMOVE")}}}}};if(show)EmployeeCreateDialog({show=false},reload);edit?.let{EnrollDialog(it,{edit=null},reload)};preview?.let{PhotoPreviewDialog(it){preview=null}}}}
 @Composable private fun PhotoPreviewDialog(employee:Employee,close:()->Unit){Dialog(onDismissRequest=close){Card(Modifier.fillMaxWidth().padding(20.dp)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(employee.name,fontSize=22.sp);Text("${employee.code} • Staff photo",fontSize=13.sp);Spacer(Modifier.height(12.dp));AsyncImage(model=employee.photoUrl,contentDescription="${employee.name} staff photo",contentScale=ContentScale.Fit,modifier=Modifier.fillMaxWidth().heightIn(min=220.dp,max=480.dp),onError={});Spacer(Modifier.height(12.dp));Text("PHOTO: OK ✓",fontSize=14.sp);Spacer(Modifier.height(8.dp));Button(onClick=close,modifier=Modifier.fillMaxWidth()){Text("CLOSE")}}}}}
 @Composable private fun EmployeeCreateDialog(close:()->Unit,reload:()->Unit){var code by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var dept by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Add employee")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(code,{code=it},label={Text("Employee code")});OutlinedTextField(name,{name=it},label={Text("Name")});OutlinedTextField(dept,{dept=it},label={Text("Department")});Text(msg)}},confirmButton={Button({createEmployee(code,name,dept){ok,m->msg=m;if(ok){reload();close()}}}){Text("CREATE")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 @Composable private fun EnrollDialog(existing:Employee,close:()->Unit,reload:()->Unit){var photo by remember{mutableStateOf<Bitmap?>(null)};var status by remember{mutableStateOf(if(existing.photoUrl.isNullOrBlank())"Staff photo: NOT UPLOADED"else"Staff photo: OK ✓")};var saving by remember{mutableStateOf(false)};val gallery=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri->if(uri!=null){executor.execute{try{val bmp=decodeGalleryPhoto(uri);runOnUiThread{photo=bmp;status="Gallery photo loaded ✓"}}catch(e:Exception){runOnUiThread{status="Gallery photo failed: ${e.message}"}}}}};val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicturePreview()){bmp->if(bmp!=null){photo=bmp;status="Camera photo ready ✓"}};val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){ok->if(ok)camera.launch(null)else status="Camera permission denied"};AlertDialog(onDismissRequest={if(!saving)close()},title={Text("Staff photo — ${existing.name}")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){photo?.let{Image(bitmap=it.asImageBitmap(),contentDescription="Selected staff photo",contentScale=ContentScale.Crop,modifier=Modifier.fillMaxWidth().height(180.dp))};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(enabled=!saving,onClick={permission.launch(android.Manifest.permission.CAMERA)}){Text("CAMERA")};OutlinedButton(enabled=!saving,onClick={gallery.launch("image/*")}){Text("GALLERY")}};Text(if(photo==null)"No new photo selected"else"Photo selected ✓");if(saving){LinearProgressIndicator(modifier=Modifier.fillMaxWidth());Text("Uploading photo and enrolling face…")}else Text(status);Text(if(existing.enrolled)"Face recognition: OK ✓"else"Face recognition: NOT SET")}},confirmButton={Button(enabled=!saving,onClick={photo?.let{saving=true;status="Preparing face…";enrollFace(existing.id,it){ok,m->saving=false;status=m;if(ok){reload();close()}}}?:run{status="Please take or select a photo"}}){Text(if(saving)"SAVING…" else "SAVE PHOTO")}},dismissButton={TextButton(enabled=!saving,onClick=close){Text("CANCEL")}})}
 private fun decodeGalleryPhoto(uri:Uri):Bitmap{val opts=BitmapFactory.Options().apply{inJustDecodeBounds=true};contentResolver.openInputStream(uri).use{BitmapFactory.decodeStream(it,null,opts)};if(opts.outWidth<=0||opts.outHeight<=0)error("Selected file is not a valid image");var sample=1;while(opts.outWidth/sample>1600||opts.outHeight/sample>1600)sample*=2;val decoded=BitmapFactory.Options().apply{inSampleSize=sample;inPreferredConfig=Bitmap.Config.ARGB_8888};val bmp=contentResolver.openInputStream(uri).use{BitmapFactory.decodeStream(it,null,decoded)}?:error("Could not read gallery image");val orientation=contentResolver.openInputStream(uri).use{ExifInterface(it!!).getAttributeInt(ExifInterface.TAG_ORIENTATION,ExifInterface.ORIENTATION_NORMAL)};val m=android.graphics.Matrix();when(orientation){ExifInterface.ORIENTATION_ROTATE_90->m.postRotate(90f);ExifInterface.ORIENTATION_ROTATE_180->m.postRotate(180f);ExifInterface.ORIENTATION_ROTATE_270->m.postRotate(270f);ExifInterface.ORIENTATION_FLIP_HORIZONTAL->m.preScale(-1f,1f);ExifInterface.ORIENTATION_FLIP_VERTICAL->m.preScale(1f,-1f)};return if(!m.isIdentity)Bitmap.createBitmap(bmp,0,0,bmp.width,bmp.height,m,true)else bmp}
 @Composable private fun AttendanceList(list:List<Attendance>){Column{Text("Attendance",fontSize=24.sp);LazyColumn{items(list){a->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(a.employee,fontSize=17.sp);Text("${a.code} • ${a.status} • ${a.time}");Text(a.device);if(!a.photo.isNullOrBlank()){Button({startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(a.photo)))}){Text("VIEW PHOTO")}}}}}}}}
 @Composable private fun DeviceList(list:List<Device>,employees:List<Employee>,reload:()->Unit){var add by remember{mutableStateOf(false)};var selected by remember{mutableStateOf<Device?>(null)};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Devices",fontSize=24.sp);Button({add=true}){Text("+ ADD DEVICE")}};LazyColumn{items(list){d->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(d.name,fontSize=18.sp);Text("${d.status.uppercase()} • ${d.assigned} assigned");d.code?.let{Text("PAIRING CODE: $it",fontSize=20.sp)};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){Button({selected=d}){Text("ASSIGN STAFF")};Button({regenerateDevice(d.id,reload)}){Text("NEW CODE")};Button({removeDevice(d.id,reload)}){Text("REMOVE")}}}}}};if(add)AddDeviceDialog({add=false},reload);selected?.let{AssignmentDialog(it,employees,{selected=null},reload)}}}
 @Composable private fun AddDeviceDialog(close:()->Unit,reload:()->Unit){var name by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Add device")},text={Column{OutlinedTextField(name,{name=it},label={Text("Device name")});Text(msg)}},confirmButton={Button({createDevice(name){ok,m->msg=m;if(ok){reload();close()}}}){Text("CREATE")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 @Composable private fun AssignmentDialog(device:Device,employees:List<Employee>,close:()->Unit,reload:()->Unit){var ids by remember{mutableStateOf(setOf<String>())};var loaded by remember{mutableStateOf(false)};var msg by remember{mutableStateOf("")};LaunchedEffect(device.id){loadAssignments(device.id){ids=it.toSet();loaded=true}};AlertDialog(onDismissRequest=close,title={Text("Assign staff — ${device.name}")},text={if(!loaded)Text("Loading…")else Column{LazyColumn{items(employees.filter{it.active}){e->Row(verticalAlignment=Alignment.CenterVertically){Checkbox(ids.contains(e.id),{checked->ids=if(checked)ids+e.id else ids-e.id});Text("${e.name} (${e.code})")}}};Text(msg)}},confirmButton={Button({saveAssignments(device.id,ids.toList()){ok,m->msg=m;if(ok){reload();close()}}}){Text("SAVE")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 private fun login(email:String,password:String,done:(Boolean,String)->Unit)=executor.execute{try{val body=JSONObject().put("email",email).put("password",password).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/login").post(body).build()).execute().use{r->if(!r.isSuccessful)error("Login failed (${r.code})");token=JSONObject(r.body?.string()?:"{}").getString("token")};getSharedPreferences("admin",0).edit().putString("token",token).apply();runOnUiThread{done(true,"Logged in")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Login failed")}}}
 private fun auth(path:String)=Request.Builder().url(baseUrl+path).header("Authorization","Bearer ${token?:""}")
 private fun get(path:String)=http.newCall(auth(path).get().build()).execute().use{r->if(!r.isSuccessful)error("HTTP ${r.code}");r.body?.string()?:("{}")}
 private fun post(path:String,json:String)=http.newCall(auth(path).post(json.toRequestBody("application/json".toMediaType())).build()).execute().use{r->if(!r.isSuccessful)error("HTTP ${r.code}: ${r.body?.string()}");r.body?.string()?:("{}")}
 private fun put(path:String,json:String)=http.newCall(auth(path).put(json.toRequestBody("application/json".toMediaType())).build()).execute().use{r->if(!r.isSuccessful)error("HTTP ${r.code}: ${r.body?.string()}");r.body?.string()?:("{}")}
 private fun delete(path:String)=http.newCall(auth(path).delete().build()).execute().use{r->if(!r.isSuccessful)error("HTTP ${r.code}: ${r.body?.string()}")}
 private fun loadEmployees(done:(List<Employee>)->Unit)=executor.execute{try{val a=JSONObject(get("/api/v1/admin/employees")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Employee(x.getString("id"),x.getString("employee_code"),x.getString("name"),x.optString("department").ifBlank{null},x.optBoolean("face_enrolled"),x.optBoolean("active",true),x.optString("face_photo_secure_url").ifBlank{null})};runOnUiThread{done(o)}}catch(_:Exception){runOnUiThread{done(emptyList())}}}
 private fun loadAttendance(done:(List<Attendance>)->Unit)=executor.execute{try{val a=JSONObject(get("/api/v1/admin/attendance")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Attendance(x.optString("employee_name"),x.optString("employee_code"),x.optString("status"),x.optString("captured_at"),x.optString("device_name"),x.optString("photo_secure_url"))};runOnUiThread{done(o)}}catch(_:Exception){runOnUiThread{done(emptyList())}}}
 private fun loadDevices(done:(List<Device>)->Unit)=executor.execute{try{val a=JSONObject(get("/api/v1/admin/devices")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Device(x.getString("id"),x.getString("name"),x.optString("status"),x.optString("pairing_code").ifBlank{null},x.optInt("assigned_employees"))};runOnUiThread{done(o)}}catch(_:Exception){runOnUiThread{done(emptyList())}}}
 private fun createEmployee(code:String,name:String,dept:String,done:(Boolean,String)->Unit)=executor.execute{try{if(code.isBlank()||name.isBlank())error("Employee code and name are required");post("/api/v1/admin/employees",JSONObject().put("employeeCode",code.trim()).put("name",name.trim()).put("department",dept.trim()).toString());runOnUiThread{done(true,"Employee created — enroll the face next")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Create failed")}}}
 private fun createDevice(name:String,done:(Boolean,String)->Unit)=executor.execute{try{if(name.isBlank())error("Device name is required");val x=JSONObject(post("/api/v1/admin/devices",JSONObject().put("name",name.trim()).toString())).getJSONObject("device");runOnUiThread{done(true,"Created. Pairing code: ${x.optString("pairing_code")}" )}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Create failed")}}}
 private fun regenerateDevice(id:String,reload:()->Unit)=executor.execute{runCatching{post("/api/v1/admin/devices/$id/regenerate-code","{}");runOnUiThread{reload()}}}
 private fun removeDevice(id:String,reload:()->Unit)=executor.execute{runCatching{delete("/api/v1/admin/devices/$id");runOnUiThread{reload()}}}
 private fun removeEmployee(id:String,reload:()->Unit)=executor.execute{runCatching{delete("/api/v1/admin/employees/$id");runOnUiThread{reload()}}}
 private fun loadAssignments(id:String,done:(List<String>)->Unit)=executor.execute{try{val a=JSONObject(get("/api/v1/admin/devices/$id/assignments")).getJSONArray("employeeIds");runOnUiThread{done(List(a.length()){a.getString(it)})}}catch(_:Exception){runOnUiThread{done(emptyList())}}}
 private fun saveAssignments(id:String,ids:List<String>,done:(Boolean,String)->Unit)=executor.execute{try{post("/api/v1/admin/devices/$id/assign",JSONObject().put("employeeIds",JSONArray(ids)).toString());runOnUiThread{done(true,"Saved")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Save failed")}}}
 private fun enrollFace(id:String,bmp:Bitmap,done:(Boolean,String)->Unit)=executor.execute{try{val detector=FaceDetection.getClient(FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).build());detector.process(InputImage.fromBitmap(bmp,0)).addOnSuccessListener{faces->if(faces.size!=1){runOnUiThread{done(false,"Use a photo containing exactly one face")};return@addOnSuccessListener};val emb=runCatching{FaceNetEmbedder(this@MainActivity).use{it.embed(crop(bmp,faces[0].boundingBox))}}.getOrElse{runOnUiThread{done(false,"FaceNet error: ${it.message}")};return@addOnSuccessListener};val arr=JSONArray();emb.forEach{arr.put(it.toDouble())};executor.execute{try{val photoUrl=uploadStaffPhoto(bmp);put("/api/v1/admin/employees/$id/face",JSONObject().put("faceTemplate",arr).put("facePhotoSecureUrl",photoUrl).toString());runOnUiThread{done(true,"PHOTO: OK ✓  •  FACE: OK ✓")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Update failed")}}}}.addOnFailureListener{runOnUiThread{done(false,"Face detection failed: ${it.message}")}}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Photo error")}}}
 private fun uploadStaffPhoto(bitmap:Bitmap):String{val file=java.io.File(cacheDir,"staff_photo_${System.currentTimeMillis()}.jpg");file.outputStream().use{bitmap.compress(CompressFormat.JPEG,90,it)};val sig=JSONObject(get("/api/v1/admin/cloudinary/signature"));val body=MultipartBody.Builder().setType(MultipartBody.FORM).addFormDataPart("file",file.name,file.asRequestBody("image/jpeg".toMediaType())).addFormDataPart("api_key",sig.getString("apiKey")).addFormDataPart("timestamp",sig.getString("timestamp")).addFormDataPart("folder",sig.getString("folder")).addFormDataPart("signature",sig.getString("signature")).build();val req=Request.Builder().url("https://api.cloudinary.com/v1_1/${sig.getString("cloudName")}/image/upload").post(body).build();return http.newCall(req).execute().use{r->if(!r.isSuccessful)error("Cloudinary upload failed (${r.code})");JSONObject(r.body?.string()?:"{}").getString("secure_url")}.also{file.delete()}}
 private fun crop(src:Bitmap,box:Rect):Bitmap{val p=(box.width().coerceAtLeast(box.height())*.35f).toInt();val l=(box.left-p).coerceIn(0,src.width-1);val t=(box.top-p).coerceIn(0,src.height-1);val r=(box.right+p).coerceIn(l+1,src.width);val b=(box.bottom+p).coerceIn(t+1,src.height);return Bitmap.createBitmap(src,l,t,r-l,b-t)}
}
