package com.streetbell.admin

import android.app.DatePickerDialog
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Rect
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDate
import java.util.concurrent.Executors

private data class Employee(val id:String,val code:String,val name:String,val department:String?,val active:Boolean,val enrolled:Boolean)
private data class Device(val id:String,val name:String,val status:String,val code:String?,val assigned:Int)
private data class Attendance(val employee:String,val code:String,val status:String,val time:String,val device:String,val photo:String?)

class MainActivity:ComponentActivity(){
 private val http=OkHttpClient();private val executor=Executors.newCachedThreadPool();private val baseUrl="https://attendance-backend-rkny.onrender.com";private var token:String?=null;private var selectedPhoto:Uri?=null;private var photoCallback:(()->Unit)?=null
 private val picker=registerForActivityResult(ActivityResultContracts.GetContent()){selectedPhoto=it;photoCallback?.invoke()}
 override fun onCreate(b:Bundle?){super.onCreate(b);token=getSharedPreferences("admin",0).getString("token",null);setContent{App()}}
 @Composable private fun App(){var logged by remember{mutableStateOf(token!=null)};if(!logged)Login{logged=true}else Dashboard{token=null;getSharedPreferences("admin",0).edit().remove("token").apply();logged=false}}
 @Composable private fun Login(ok:()->Unit){var email by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("ATTEND ADMIN",fontSize=32.sp);Spacer(Modifier.height(20.dp));OutlinedTextField(email,{email=it},label={Text("Email")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(pass,{pass=it},label={Text("Password")},singleLine=true,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(12.dp));Button({login(email,pass){success,text->msg=text;if(success)ok()}},Modifier.fillMaxWidth()){Text("LOGIN")};Text(msg)}}
 @Composable private fun Dashboard(logout:()->Unit){var tab by remember{mutableStateOf("Staff")};var employees by remember{mutableStateOf(emptyList<Employee>())};var devices by remember{mutableStateOf(emptyList<Device>())};var attendance by remember{mutableStateOf(emptyList<Attendance>())};var refresh by remember{mutableStateOf(0)};LaunchedEffect(refresh){loadEmployees{employees=it};loadDevices{devices=it};loadAttendance("",""){attendance=it}};Scaffold(topBar={TopAppBar(title={Text("ATTEND ADMIN")},actions={TextButton({refresh++}){Text("SYNC")};TextButton(logout){Text("LOG OUT")}})},bottomBar={NavigationBar{listOf("Staff","Attendance","Devices").forEach{n->NavigationBarItem(selected=tab==n,onClick={tab=n},icon={Text(n.first().toString())},label={Text(n)})}}}){p->Column(Modifier.fillMaxSize().padding(p).padding(16.dp)){when(tab){"Staff"->Staff(employees){refresh++};"Attendance"->AttendanceScreen(employees,attendance){f,t->loadAttendance(f,t){attendance=it}};"Devices"->Devices(devices,employees){refresh++}}}}}
 @Composable private fun Staff(list:List<Employee>,reload:()->Unit){var add by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<Employee?>(null)};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text("Staff",fontSize=26.sp);Button({add=true}){Text("+ ADD")}};Text("${list.size} employees");LazyColumn{items(list){e->Card(Modifier.fillMaxWidth().padding(vertical=4.dp),onClick={edit=e}){Column(Modifier.padding(14.dp)){Text(e.name,fontSize=18.sp);Text("${e.code} • ${e.department.orEmpty()}");Text(if(e.enrolled)"Face enrolled (FaceNet)"else"Face not enrolled")}}}}};if(add)EmployeeEditor(null,{add=false},reload);if(edit!=null)EmployeeEditor(edit!!,{edit=null},reload)}
 @Composable private fun EmployeeEditor(existing:Employee?,close:()->Unit,reload:()->Unit){var code by remember{mutableStateOf(existing?.code?:"")};var name by remember{mutableStateOf(existing?.name?:"")};var dept by remember{mutableStateOf(existing?.department?:"")};var photo by remember{mutableStateOf<Uri?>(null)};var status by remember{mutableStateOf("")};photoCallback={photo=selectedPhoto};AlertDialog(onDismissRequest=close,title={Text(if(existing==null)"Add staff"else"Re-enroll face")},text={Column{if(existing==null){OutlinedTextField(code,{code=it},label={Text("Employee ID")});OutlinedTextField(name,{name=it},label={Text("Full name")});OutlinedTextField(dept,{dept=it},label={Text("Department")})};Spacer(Modifier.height(8.dp));OutlinedButton({picker.launch("image/*")}){Text(if(photo==null)"Select face photo"else"Photo selected")};Text(status)}},confirmButton={Button(enabled=photo!=null,onClick={status="Generating FaceNet embedding…";if(existing==null)createEmployee(code,name,dept,photo!!){ok,msg->{status=msg;if(ok){reload();close()}}}else{updateFace(existing.id,photo!!){ok,msg->{status=msg;if(ok){reload();close()}}}}}){Text(if(existing==null)"CREATE"else"RE-ENROLL")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 @Composable private fun AttendanceScreen(employees:List<Employee>,list:List<Attendance>,search:(String,String)->Unit){var from by remember{mutableStateOf(LocalDate.now().withDayOfMonth(1).toString())};var to by remember{mutableStateOf(LocalDate.now().toString())};Column{Text("Attendance",fontSize=26.sp);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({pick(from){from=it}},Modifier.weight(1f)){Text("FROM\n$from")};Button({pick(to){to=it}},Modifier.weight(1f)){Text("TO\n$to")}};Button({search(from,to)},Modifier.fillMaxWidth()){Text("VIEW")};LazyColumn{items(list){a->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(a.employee);Text("${a.code} • ${a.status} • ${a.time}");Text(a.device);if(!a.photo.isNullOrBlank())Text("PHOTO ✓")}}}}}}
 private fun pick(value:String,done:(String)->Unit){val d=runCatching{LocalDate.parse(value)}.getOrElse{LocalDate.now()};DatePickerDialog(this,{_,y,m,day->done(String.format("%04d-%02d-%02d",y,m+1,day))},d.year,d.monthValue-1,d.dayOfMonth).show()}
 @Composable private fun Devices(list:List<Device>,employees:List<Employee>,reload:()->Unit){var create by remember{mutableStateOf(false)};var assign by remember{mutableStateOf<Device?>(null)};Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Devices",fontSize=26.sp);Button({create=true}){Text("+ ADD")}};LazyColumn{items(list){d->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(14.dp)){Text(d.name,fontSize=18.sp);Text("${d.status.uppercase()} • ${d.assigned} assigned");d.code?.let{Text("PAIRING CODE: $it",fontSize=22.sp)};Button({assign=d}){Text("MANAGE STAFF")}}}}};if(create)CreateDevice({create=false},reload);if(assign!=null)AssignDialog(assign!!,employees,{assign=null},reload)}}
 @Composable private fun CreateDevice(close:()->Unit,reload:()->Unit){var name by remember{mutableStateOf("Attendance Kiosk")};var code by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Add device")},text={Column{OutlinedTextField(name,{name=it},label={Text("Device name")});if(code.isNotBlank())Text("PAIRING CODE\n$code",fontSize=25.sp)}},confirmButton={Button(enabled=code.isBlank(),onClick={createDevice(name){code=it;reload()}}){Text("GENERATE")}},dismissButton={TextButton(close){Text("DONE")}})}
 @Composable private fun AssignDialog(d:Device,employees:List<Employee>,close:()->Unit,reload:()->Unit){var selected by remember{mutableStateOf(setOf<String>())};LaunchedEffect(d.id){loadAssignments(d.id){selected=it}};AlertDialog(onDismissRequest=close,title={Text("Manage staff")},text={LazyColumn{items(employees){e->Row(verticalAlignment=Alignment.CenterVertically){Checkbox(selected.contains(e.id),{selected=if(it)selected+e.id else selected-e.id});Text("${e.name} • ${e.code}")}}}},confirmButton={Button({assign(d.id,selected.toList()){reload();close()}}){Text("SAVE")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 private fun login(email:String,password:String,done:(Boolean,String)->Unit)=executor.execute{try{val b=JSONObject().put("email",email).put("password",password).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/login").post(b).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Login failed (${r.code})");token=JSONObject(r.body?.string()?:"{}").getString("token")};getSharedPreferences("admin",0).edit().putString("token",token).apply();runOnUiThread{done(true,"Logged in")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Login failed")}}}
 private fun call(path:String):String{val r=http.newCall(Request.Builder().url(baseUrl+path).header("Authorization","Bearer $token").get().build()).execute();if(!r.isSuccessful)throw Exception("HTTP ${r.code}");return r.body?.string()?:"{}"}
 private fun loadEmployees(done:(List<Employee>)->Unit)=executor.execute{try{val a=JSONObject(call("/api/v1/admin/employees")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Employee(x.getString("id"),x.getString("employee_code"),x.getString("name"),x.optString("department").ifBlank{null},x.optBoolean("active",true),x.optBoolean("face_enrolled",false))};runOnUiThread{done(o)}}catch(_:Exception){}}
 private fun loadDevices(done:(List<Device>)->Unit)=executor.execute{try{val a=JSONObject(call("/api/v1/admin/devices")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Device(x.getString("id"),x.getString("name"),x.getString("status"),x.optString("pairing_code").ifBlank{null},x.optInt("assigned_employees",0))};runOnUiThread{done(o)}}catch(_:Exception){}}
 private fun loadAssignments(id:String,done:(Set<String>)->Unit)=executor.execute{try{val a=JSONObject(call("/api/v1/admin/devices/$id/assignments")).getJSONArray("employeeIds");runOnUiThread{done(buildSet{for(i in 0 until a.length())add(a.getString(i))})}}catch(_:Exception){runOnUiThread{done(emptySet())}}}
 private fun assign(id:String,ids:List<String>,done:()->Unit)=executor.execute{try{val a=JSONArray();ids.forEach{a.put(it)};val b=JSONObject().put("employeeIds",a).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/devices/$id/assign").header("Authorization","Bearer $token").post(b).build()).execute().use{if(!it.isSuccessful)throw Exception()};runOnUiThread(done)}catch(_:Exception){}}
 private fun createDevice(name:String,done:(String)->Unit)=executor.execute{try{val b=JSONObject().put("name",name).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/devices").header("Authorization","Bearer $token").post(b).build()).execute().use{r->if(!r.isSuccessful)throw Exception();done(JSONObject(r.body?.string()?:"{}").getJSONObject("device").getString("pairing_code"))}}catch(_:Exception){}}
 private fun createEmployee(code:String,name:String,dept:String,uri:Uri,done:(Boolean,String)->Unit){executor.execute{try{val bmp=contentResolver.openInputStream(uri)?.use{BitmapFactory.decodeStream(it)}?:error("Invalid image");val detector=FaceDetection.getClient(FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).build());detector.process(InputImage.fromBitmap(bmp,0)).addOnSuccessListener{faces->if(faces.size!=1){done(false,if(faces.isEmpty())"No face detected"else"Use one-face photo");return@addOnSuccessListener};val crop=crop(bmp,faces[0].boundingBox);val emb=runCatching{FaceNetEmbedder(this).use{it.embed(crop)}}.getOrElse{done(false,"FaceNet error: ${it.message}");return@addOnSuccessListener};postEmployee(code,name,dept,emb,done)}.addOnFailureListener{done(false,"Face detection failed: ${it.message}")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Photo error")}}}}
 private fun updateFace(id:String,uri:Uri,done:(Boolean,String)->Unit){executor.execute{try{val bmp=contentResolver.openInputStream(uri)?.use{BitmapFactory.decodeStream(it)}?:error("Invalid image");val detector=FaceDetection.getClient(FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).build());detector.process(InputImage.fromBitmap(bmp,0)).addOnSuccessListener{faces->if(faces.size!=1){done(false,"Use a photo with exactly one face");return@addOnSuccessListener};val emb=runCatching{FaceNetEmbedder(this).use{it.embed(crop(bmp,faces[0].boundingBox))}}.getOrElse{done(false,"FaceNet error: ${it.message}");return@addOnSuccessListener};val a=JSONArray();emb.forEach{a.put(it.toDouble())};val body=JSONObject().put("faceTemplate",a).toString().toRequestBody("application/json".toMediaType());executor.execute{try{http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/employees/$id/face").header("Authorization","Bearer $token").put(body).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Update failed (${r.code})")};runOnUiThread{done(true,"Face re-enrolled")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Update failed")}}}}.addOnFailureListener{done(false,"Face detection failed")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Photo error")}}}}
 private fun postEmployee(code:String,name:String,dept:String,emb:FloatArray,done:(Boolean,String)->Unit){val a=JSONArray();emb.forEach{a.put(it.toDouble())};val body=JSONObject().put("employeeCode",code).put("name",name).put("department",dept).put("faceTemplate",a).toString().toRequestBody("application/json".toMediaType());executor.execute{try{http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/employees").header("Authorization","Bearer $token").post(body).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Create failed (${r.code})")};runOnUiThread{done(true,"Employee created")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Create failed")}}}}
 private fun crop(src:Bitmap,box:Rect):Bitmap{val p=(box.width().coerceAtLeast(box.height())*.35f).toInt();val l=(box.left-p).coerceIn(0,src.width-1);val t=(box.top-p).coerceIn(0,src.height-1);val r=(box.right+p).coerceIn(l+1,src.width);val b=(box.bottom+p).coerceIn(t+1,src.height);return Bitmap.createBitmap(src,l,t,r-l,b-t)}
 private fun loadAttendance(from:String,to:String,done:(List<Attendance>)->Unit)=executor.execute{try{val q=if(from.isBlank())"" else "?from=$from&to=$to";val a=JSONObject(call("/api/v1/admin/attendance$q")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Attendance(x.getString("employee_name"),x.getString("employee_code"),x.getString("status"),x.getString("captured_at"),x.getString("device_name"),x.optString("photo_secure_url").ifBlank{null})};runOnUiThread{done(o)}}catch(_:Exception){runOnUiThread{done(emptyList())}}}
}
