package com.streetbell.admin

import android.app.DatePickerDialog
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Rect
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.RowScope
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.weight
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDate
import java.util.concurrent.Executors
import kotlin.math.sqrt

private data class Employee(val id:String,val code:String,val name:String,val department:String?,val active:Boolean)
private data class Device(val id:String,val name:String,val status:String,val pairingCode:String?,val lastSeen:String?)
private data class Attendance(val employeeId:String?,val employee:String,val code:String,val status:String,val time:String,val device:String,val photo:String?)
private data class Summary(val events:Int,val ins:Int,val outs:Int,val presentDays:Int,val absentDays:Int,val hours:String)

class MainActivity:ComponentActivity(){
 private val http=OkHttpClient();private val executor=Executors.newCachedThreadPool();private val baseUrl="https://attendance-backend-rkny.onrender.com";private var token:String?=null;private var selectedPhoto:Uri?=null;private var photoChanged:(()->Unit)?=null
 private val picker=registerForActivityResult(ActivityResultContracts.GetContent()){u->selectedPhoto=u;photoChanged?.invoke()}
 override fun onCreate(s:Bundle?){super.onCreate(s);token=getSharedPreferences("admin",0).getString("token",null);setContent{App()}}
 @Composable private fun App(){var logged by remember{mutableStateOf(token!=null)};var email by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};var msg by remember{mutableStateOf("")};if(!logged){Column(Modifier.fillMaxSize().padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("ATTEND",fontSize=38.sp,fontWeight=FontWeight.Bold);Text("Admin Console",color=Color.Gray);Spacer(Modifier.height(24.dp));OutlinedTextField(email,{email=it},label={Text("Email")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(pass,{pass=it},label={Text("Password")},singleLine=true,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(16.dp));Button({login(email,pass){ok,t->msg=t;if(ok)logged=true}},Modifier.fillMaxWidth()){Text("LOGIN")};if(msg.isNotBlank())Text(msg,color=Color.Gray)}}else Shell{token=null;getSharedPreferences("admin",0).edit().remove("token").apply();logged=false}}
 @Composable private fun Shell(logout:()->Unit){var tab by remember{mutableStateOf("Home")};var e by remember{mutableStateOf(emptyList<Employee>())};var d by remember{mutableStateOf(emptyList<Device>())};var a by remember{mutableStateOf(emptyList<Attendance>())};var s by remember{mutableStateOf(Summary(0,0,0,0,0,"0h 0m"))};var refresh by remember{mutableStateOf(0)};LaunchedEffect(refresh){loadEmployees{e=it};loadDevices{d=it};loadAttendance("","",""){x,y->a=x;s=y}};Scaffold(bottomBar={NavigationBar{listOf("Home","Staff","Attendance","Devices","More").forEach{n->NavigationBarItem(selected=tab==n,onClick={tab=n},icon={Text(n.first().toString())},label={Text(n)})}}}){p->Column(Modifier.fillMaxSize().padding(p).padding(18.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("ATTEND",fontSize=28.sp,fontWeight=FontWeight.Bold);Text("Admin control center",color=Color.Gray)};TextButton({refresh++}){Text("SYNC")}};Spacer(Modifier.height(12.dp));when(tab){"Home"->Home(e,d,a,s);"Staff"->Staff(e){refresh++};"Attendance"->AttendanceScreen(e,a,s){f,t,id->loadAttendance(f,t,id){x,y->a=x;s=y}};"Devices"->Devices(d,e){refresh++};else->More(logout)}}}}
 @Composable private fun Home(e:List<Employee>,d:List<Device>,a:List<Attendance>,s:Summary){Text("Today",fontSize=25.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("Staff",e.size.toString());Stat("Present",s.presentDays.toString());Stat("IN",s.ins.toString());Stat("OUT",s.outs.toString())};Spacer(Modifier.height(18.dp));Text("Devices",fontSize=20.sp,fontWeight=FontWeight.Bold);d.take(3).forEach{DeviceCard(it,{},false)};Spacer(Modifier.height(12.dp));Text("Recent attendance",fontSize=20.sp,fontWeight=FontWeight.Bold);LazyColumn{items(a.take(8)){AttendanceCard(it)}}}
 @Composable private fun RowScope.Stat(t:String,v:String){Card(Modifier.weight(1f),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=Color(0xFFF0F0EE))){Column(Modifier.padding(13.dp)){Text(v,fontSize=24.sp,fontWeight=FontWeight.Bold);Text(t,color=Color.Gray)}}}
 @Composable private fun Staff(list:List<Employee>,reload:()->Unit){var open by remember{mutableStateOf(false)};var q by remember{mutableStateOf("")};var detail by remember{mutableStateOf<Employee?>(null)};Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("Staff",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("${list.size} employees",color=Color.Gray)};Button({open=true}){Text("+ ADD")}};Spacer(Modifier.height(8.dp));OutlinedTextField(q,{q=it},label={Text("Search staff")},singleLine=true,modifier=Modifier.fillMaxWidth());LazyColumn{items(list.filter{it.name.contains(q,true)||it.code.contains(q,true)||it.department.orEmpty().contains(q,true)}){x->Card(Modifier.fillMaxWidth().padding(vertical=4.dp),shape=RoundedCornerShape(16.dp),onClick={detail=x}){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(x.name,fontWeight=FontWeight.Bold);Text("${x.code} • ${x.department.orEmpty().ifBlank{"No department"}}",color=Color.Gray)};Text(if(x.active)"ACTIVE"else"INACTIVE",fontSize=11.sp)}}}}};if(open)AddEmployee({open=false},reload);detail?.let{EmployeeDialog(it){detail=null}}}
 @Composable private fun AddEmployee(close:()->Unit,reload:()->Unit){var code by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var dept by remember{mutableStateOf("")};var photo by remember{mutableStateOf<Uri?>(null)};var status by remember{mutableStateOf("")};photoChanged={photo=selectedPhoto};AlertDialog(onDismissRequest=close,title={Text("Add staff")},text={Column{OutlinedTextField(code,{code=it},label={Text("Employee ID")});OutlinedTextField(name,{name=it},label={Text("Full name")});OutlinedTextField(dept,{dept=it},label={Text("Department")});Spacer(Modifier.height(8.dp));OutlinedButton({picker.launch("image/*")}){Text(if(photo==null)"Select face photo"else"Face photo selected")};if(status.isNotBlank())Text(status)}},confirmButton={Button(enabled=code.isNotBlank()&&name.isNotBlank()&&photo!=null,onClick={status="Enrolling face…";createEmployee(code,name,dept,photo!!){ok,t->status=t;if(ok){reload();close()}}}){Text("CREATE")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 @Composable private fun EmployeeDialog(e:Employee,close:()->Unit){AlertDialog(onDismissRequest=close,title={Text(e.name)},text={Column{Text("${e.code} • ${e.department.orEmpty()}");Text(if(e.active)"Active"else"Inactive");Text("Face enrollment: ✓");Text("Use Attendance to view this staff member by date range.")}},confirmButton={TextButton(close){Text("CLOSE")}})}
 @Composable private fun AttendanceScreen(employees:List<Employee>,list:List<Attendance>,s:Summary,search:(String,String,String)->Unit){var employee by remember{mutableStateOf<Employee?>(null)};var from by remember{mutableStateOf(LocalDate.now().withDayOfMonth(1).toString())};var to by remember{mutableStateOf(LocalDate.now().toString())};var choose by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize()){Text("Attendance",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("View attendance by staff with FROM / TO dates",color=Color.Gray);Spacer(Modifier.height(12.dp));OutlinedButton({choose=true},Modifier.fillMaxWidth()){Text(employee?.let{"${it.name} • ${it.code}"}?:"ALL STAFF")};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({pickDate(from){from=it}},Modifier.weight(1f)){Text("FROM\n$from")};OutlinedButton({pickDate(to){to=it}},Modifier.weight(1f)){Text("TO\n$to")}};Button({search(from,to,employee?.id.orEmpty())},Modifier.fillMaxWidth()){Text("VIEW ATTENDANCE")};Spacer(Modifier.height(10.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Stat("Events",s.events.toString());Stat("IN",s.ins.toString());Stat("OUT",s.outs.toString())};Spacer(Modifier.height(10.dp));LazyColumn{items(list){AttendanceCard(it)}}};if(choose)EmployeePicker(employees,{employee=it;choose=false},{choose=false})}
 private fun pickDate(current:String,done:(String)->Unit){val d=runCatching{LocalDate.parse(current)}.getOrElse{LocalDate.now()};DatePickerDialog(this,{_,y,m,day->done(String.format("%04d-%02d-%02d",y,m+1,day))},d.year,d.monthValue-1,d.dayOfMonth).show()}
 @Composable private fun EmployeePicker(list:List<Employee>,select:(Employee?)->Unit,close:()->Unit){AlertDialog(onDismissRequest=close,title={Text("Select staff")},text={LazyColumn(Modifier.heightIn(max=400.dp)){item{TextButton({select(null)}){Text("ALL STAFF")}};items(list){e->TextButton({select(e)}){Text("${e.name} • ${e.code}")}}}},confirmButton={TextButton(close){Text("CLOSE")}})}
 @Composable private fun AttendanceCard(a:Attendance){Card(Modifier.fillMaxWidth().padding(vertical=4.dp),shape=RoundedCornerShape(16.dp)){Row(Modifier.fillMaxWidth().padding(14.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(a.employee,fontWeight=FontWeight.Bold);Text("${a.code} • ${a.time}",color=Color.Gray);Text(a.device,color=Color.Gray)};Column(horizontalAlignment=Alignment.End){Text(a.status,fontWeight=FontWeight.Bold);if(!a.photo.isNullOrBlank())Text("PHOTO ✓",fontSize=10.sp)}}}}
 @Composable private fun Devices(list:List<Device>,employees:List<Employee>,reload:()->Unit){var create by remember{mutableStateOf(false)};var assign by remember{mutableStateOf<Device?>(null)};Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("Devices",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("Attendance terminals",color=Color.Gray)};Button({create=true}){Text("+ ADD DEVICE")}};Spacer(Modifier.height(8.dp));LazyColumn{items(list){d->DeviceCard(d,{assign=d},true)}}};if(create)CreateDevice({create=false},reload);assign?.let{AssignDialog(it,employees,{assign=null},reload)}}
 @Composable private fun DeviceCard(d:Device,click:()->Unit,manage:Boolean){Card(Modifier.fillMaxWidth().padding(vertical=5.dp),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(d.name,fontSize=18.sp,fontWeight=FontWeight.Bold);Text(d.id.take(8),color=Color.Gray)};Text("● ${d.status.uppercase()}",fontSize=11.sp)};d.lastSeen?.takeIf{it.isNotBlank()}?.let{Text("Last seen $it")};d.pairingCode?.takeIf{it.isNotBlank()}?.let{Text("PAIRING CODE  $it",fontSize=18.sp,fontWeight=FontWeight.Bold);TextButton({copyCode(it)}){Text("COPY CODE")}};if(manage)Button(click){Text("MANAGE STAFF")}}}}
 @Composable private fun CreateDevice(close:()->Unit,reload:()->Unit){var name by remember{mutableStateOf("")};var code by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Create attendance device")},text={Column{Text("A one-time code will connect the Attendance app to this device.");OutlinedTextField(name,{name=it},label={Text("Device name")});if(code.isNotBlank()){Spacer(Modifier.height(10.dp));Text("PAIRING CODE",fontSize=11.sp);Text(code,fontSize=34.sp,fontWeight=FontWeight.Bold);Text("Enter this exact code in the Attendance app.");TextButton({copyCode(code)}){Text("COPY")}}}},confirmButton={Button(enabled=name.isNotBlank()&&code.isBlank(),onClick={createDevice(name){code=it;reload()}}){Text("GENERATE CODE")}},dismissButton={TextButton(close){Text(if(code.isBlank())"CLOSE"else"DONE")}})}
 @Composable private fun AssignDialog(d:Device,employees:List<Employee>,close:()->Unit,reload:()->Unit){var selected by remember{mutableStateOf(setOf<String>())};var loading by remember{mutableStateOf(true)};LaunchedEffect(d.id){loadAssignments(d.id){selected=it;loading=false}};AlertDialog(onDismissRequest=close,title={Text("Manage staff")},text={Column{Text(d.name,fontWeight=FontWeight.Bold);if(loading)Text("Loading assignments…");LazyColumn(Modifier.heightIn(max=400.dp)){items(employees){e->Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Checkbox(selected.contains(e.id),{selected=if(it)selected+e.id else selected-e.id});Text("${e.name} • ${e.code}")}}}}},confirmButton={Button({assign(d.id,selected.toList()){reload();close()}}){Text("SAVE")}},dismissButton={TextButton(close){Text("CANCEL")}})}
 @Composable private fun More(logout:()->Unit){Column(Modifier.fillMaxSize()){Text("More",fontSize=25.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));MoreRow("Business","Current business and access");MoreRow("Reports","Attendance exports and summaries");MoreRow("Notifications","Live attendance and device alerts");MoreRow("Security","Admin and device authentication");MoreRow("Settings","Application preferences");Spacer(Modifier.height(18.dp));OutlinedButton(logout,Modifier.fillMaxWidth()){Text("LOG OUT")}}}
 @Composable private fun MoreRow(a:String,b:String){Card(Modifier.fillMaxWidth().padding(vertical=4.dp),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(16.dp)){Text(a,fontWeight=FontWeight.Bold);Text(b,color=Color.Gray)}}}
 private fun login(email:String,password:String,done:(Boolean,String)->Unit)=executor.execute{try{val b=JSONObject().put("email",email).put("password",password).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/login").post(b).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Login failed (${r.code})");token=JSONObject(r.body?.string()?:"{}").getString("token")};getSharedPreferences("admin",0).edit().putString("token",token).apply();runOnUiThread{done(true,"Logged in")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Login failed")}}}
 private fun call(path:String):String{val r=http.newCall(Request.Builder().url(baseUrl+path).header("Authorization","Bearer $token").get().build()).execute();if(!r.isSuccessful)throw Exception("HTTP ${r.code}");return r.body?.string()?:"{}"}
 private fun loadEmployees(done:(List<Employee>)->Unit)=executor.execute{try{val a=JSONObject(call("/api/v1/admin/employees")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Employee(x.getString("id"),x.getString("employee_code"),x.getString("name"),x.optString("department").ifBlank{null},x.optBoolean("active",true))};runOnUiThread{done(o)}}catch(_:Exception){}}
 private fun loadDevices(done:(List<Device>)->Unit)=executor.execute{try{val a=JSONObject(call("/api/v1/admin/devices")).getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Device(x.getString("id"),x.getString("name"),x.getString("status"),x.optString("pairing_code").ifBlank{null},x.optString("last_seen_at").ifBlank{null})};runOnUiThread{done(o)}}catch(_:Exception){}}
 private fun loadAttendance(from:String,to:String,id:String,done:(List<Attendance>,Summary)->Unit)=executor.execute{try{val q=if(from.isBlank())""else"?from=$from&to=$to${if(id.isBlank())""else"&employeeId=$id"}";val j=JSONObject(call("/api/v1/admin/attendance$q"));val a=j.getJSONArray("items");val o=List(a.length()){i->val x=a.getJSONObject(i);Attendance(if(x.isNull("employee_id"))null else x.getString("employee_id"),x.getString("employee_name"),x.getString("employee_code"),x.getString("status"),x.getString("captured_at"),x.getString("device_name"),x.optString("photo_secure_url").ifBlank{null})};val z=j.optJSONObject("summary");val sum=Summary(z?.optInt("events",o.size)?:o.size,z?.optInt("ins",0)?:0,z?.optInt("outs",0)?:0,z?.optInt("presentDays",0)?:0,z?.optInt("absentDays",0)?:0,z?.optString("hours","0h 0m")?:"0h 0m");runOnUiThread{done(o,sum)}}catch(_:Exception){}}
 private fun createDevice(name:String,done:(String)->Unit)=executor.execute{try{val b=JSONObject().put("name",name).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/devices").header("Authorization","Bearer $token").post(b).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Create failed ${r.code}");val x=JSONObject(r.body?.string()?:"{}").getJSONObject("device");runOnUiThread{done(x.getString("pairing_code"))}}}catch(e:Exception){runOnUiThread{done("ERROR")}}}
 private fun loadAssignments(id:String,done:(Set<String>)->Unit)=executor.execute{try{val a=JSONObject(call("/api/v1/admin/devices/$id/assignments")).getJSONArray("employeeIds");runOnUiThread{done(buildSet{for(i in 0 until a.length())add(a.getString(i))})}}catch(_:Exception){runOnUiThread{done(emptySet())}}}
 private fun assign(id:String,ids:List<String>,done:()->Unit)=executor.execute{try{val a=JSONArray();ids.forEach{a.put(it)};val b=JSONObject().put("employeeIds",a).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/devices/$id/assign").header("Authorization","Bearer $token").post(b).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Assign failed ${r.code}")};runOnUiThread(done)}catch(_:Exception){}}
 private fun createEmployee(code:String,name:String,dept:String,uri:Uri,done:(Boolean,String)->Unit){executor.execute{try{val bmp=contentResolver.openInputStream(uri)?.use{BitmapFactory.decodeStream(it)}?:throw Exception("Invalid image");val detector=FaceDetection.getClient(FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).build());detector.process(InputImage.fromBitmap(bmp,0)).addOnSuccessListener{faces->if(faces.size!=1){runOnUiThread{done(false,if(faces.isEmpty())"No face detected"else"Use a photo with one face")};return@addOnSuccessListener};val t=template(bmp,faces[0].boundingBox)?:run{runOnUiThread{done(false,"Face enrollment failed")};return@addOnSuccessListener};executor.execute{try{val a=JSONArray();t.forEach{a.put(it.toDouble())};val b=JSONObject().put("employeeCode",code).put("name",name).put("department",dept).put("faceTemplate",a).toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/admin/employees").header("Authorization","Bearer $token").post(b).build()).execute().use{r->if(!r.isSuccessful)throw Exception("Create failed (${r.code})")};runOnUiThread{done(true,"Employee created")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Create failed")}}}}.addOnFailureListener{runOnUiThread{done(false,"Face detection failed")}}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Photo error")}}}}
 private fun template(src:Bitmap,box:Rect):FloatArray?{val p=(box.width()*.18f).toInt();val l=(box.left-p).coerceAtLeast(0);val t=(box.top-p).coerceAtLeast(0);val r=(box.right+p).coerceAtMost(src.width);val b=(box.bottom+p).coerceAtMost(src.height);if(r<=l||b<=t)return null;val s=Bitmap.createScaledBitmap(Bitmap.createBitmap(src,l,t,r-l,b-t),32,32,true);val a=FloatArray(1024);var k=0;var m=0f;for(y in 0..31)for(x in 0..31){val c=s.getPixel(x,y);val v=(.299f*((c shr 16)and 255)+.587f*((c shr 8)and 255)+.114f*(c and 255))/255f;a[k++]=v;m+=v};m/=1024f;var n=0f;for(i in a.indices){a[i]-=m;n+=a[i]*a[i]};n=sqrt(n).coerceAtLeast(.0001f);for(i in a.indices)a[i]/=n;return a}
 private fun copyCode(code:String){(getSystemService(Context.CLIPBOARD_SERVICE)as ClipboardManager).setPrimaryClip(ClipData.newPlainText("Pairing code",code))}
}
