package com.streetbell.attendance

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.graphics.*
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.*
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import okhttp3.*
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.time.Instant
import java.util.UUID
import java.util.concurrent.Executors
import kotlin.math.sqrt

private data class Person(val id:String,val name:String,val template:FloatArray)

class MainActivity:ComponentActivity(){
 private val http=OkHttpClient();private val executor=Executors.newFixedThreadPool(2);private val baseUrl="https://attendance-backend-rkny.onrender.com";private var deviceToken:String?=null;private var people=emptyList<Person>();private var capture:ImageCapture?=null;private var embedder:FaceNetEmbedder?=null;private var busy=false
 private val permission=registerForActivityResult(ActivityResultContracts.RequestPermission()){setUi()}
 override fun onCreate(b:Bundle?){super.onCreate(b);deviceToken=getSharedPreferences("attendance",0).getString("deviceToken",null);if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)permission.launch(Manifest.permission.CAMERA);else setUi();runCatching{embedder=FaceNetEmbedder(this)}}
 override fun onResume(){super.onResume();if(deviceToken!=null)refreshManifest()}
 override fun onDestroy(){embedder?.close();executor.shutdown();super.onDestroy()}
 private fun setUi(){setContent{App()}}
 @Composable private fun App(){var paired by remember{mutableStateOf(deviceToken!=null)};var code by remember{mutableStateOf("")};var message by remember{mutableStateOf(if(paired)"Syncing employees…"else"Pair this attendance device")};var detected by remember{mutableStateOf(false)};var person by remember{mutableStateOf<Person?>(null)};var score by remember{mutableStateOf(0f)};var selected by remember{mutableStateOf<String?>(null)}
  if(!paired){Column(Modifier.fillMaxSize().padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("Attendance Device",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(18.dp));OutlinedTextField(code,{code=it.uppercase()},label={Text("Pairing code")},singleLine=true);Spacer(Modifier.height(12.dp));Button({pair(code){ok,t->message=t;if(ok){paired=true;refreshManifest{message=it}}}}){Text("PAIR DEVICE")};Spacer(Modifier.height(10.dp));Text(message)};return}
  Column(Modifier.fillMaxSize().padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("Attendance",style=MaterialTheme.typography.headlineMedium);Text(message);Text("${people.size} employees loaded",style=MaterialTheme.typography.labelMedium);Spacer(Modifier.height(8.dp));if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)AndroidView({PreviewView(it).also{v->startCamera(v){d,p,s->detected=d;person=p;score=s}}},Modifier.fillMaxWidth().height(420.dp))else Text("Camera permission required");Spacer(Modifier.height(10.dp));Text(when{person!=null->"${person!!.name} • Match ${(score*100).toInt()}%";detected->"Unknown employee";else->"Stand in front of the camera"});Spacer(Modifier.height(12.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Button(enabled=person!=null&&!busy,onClick={person?.let{submit("IN",it.id,score){selected="IN";message=it}}},Modifier.weight(1f)){Text("IN")};Button(enabled=person!=null&&!busy,onClick={person?.let{submit("OUT",it.id,score){selected="OUT";message=it}}},Modifier.weight(1f)){Text("OUT")}};selected?.let{Text("Selected: $it",Modifier.padding(8.dp))}}
 }
 private fun pair(code:String,done:(Boolean,String)->Unit)=executor.execute{try{require(code.trim().length>=4){"Enter a valid pairing code"};val body=JSONObject().put("pairingCode",code.trim()).put("deviceName","Attendance Kiosk").put("appVersion","1.5.0").toString().toRequestBody("application/json".toMediaType());http.newCall(Request.Builder().url("$baseUrl/api/v1/device/pair").post(body).build()).execute().use{r->if(!r.isSuccessful)error("Pairing failed (${r.code})");deviceToken=JSONObject(r.body?.string()?:error("Empty response")).getString("deviceToken")};getSharedPreferences("attendance",MODE_PRIVATE).edit().putString("deviceToken",deviceToken).apply();runOnUiThread{done(true,"Device paired")}}catch(e:Exception){runOnUiThread{done(false,e.message?:"Pairing failed")}}}
 private fun refreshManifest(done:(String)->Unit={})=executor.execute{try{val r=http.newCall(auth(Request.Builder().url("$baseUrl/api/v1/device/manifest").get())).execute();r.use{if(!it.isSuccessful)error("Manifest error ${it.code}");val arr=JSONObject(it.body?.string()? : "{}").getJSONArray("employees");val list=mutableListOf<Person>();for(i in 0 until arr.length()){val e=arr.getJSONObject(i);if(e.optString("faceModelVersion")!="facenet-v1")continue;val a=e.optJSONArray("faceTemplate")?:continue;if(a.length()!=128)continue;list+=Person(e.getString("id"),e.getString("name"),FloatArray(128){a.getDouble(it).toFloat()})};people=list};runOnUiThread{done("Ready • ${people.size} employees")}}catch(e:Exception){runOnUiThread{done("Sync failed: ${e.message}")}}}
 private fun startCamera(view:PreviewView,onMatch:(Boolean,Person?,Float)->Unit){val future=ProcessCameraProvider.getInstance(this);future.addListener({try{val provider=future.get();val preview=Preview.Builder().build().also{it.surfaceProvider=view.surfaceProvider};capture=ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MINIMIZE_LATENCY).build();val detector=FaceDetection.getClient(FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_FAST).build());val analysis=ImageAnalysis.Builder().setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();var last=0L;analysis.setAnalyzer(executor){proxy->if(System.currentTimeMillis()-last<450){proxy.close();return@setAnalyzer};last=System.currentTimeMillis();val img=proxy.image;if(img==null){proxy.close();return@setAnalyzer};val rotation=proxy.imageInfo.rotationDegrees;detector.process(InputImage.fromMediaImage(img,rotation)).addOnSuccessListener{faces->val face=faces.maxByOrNull{it.boundingBox.width()*it.boundingBox.height()};if(face==null){onMatch(false,null,0f);return@addOnSuccessListener};val bmp=yuvToBitmap(proxy,rotation);val crop=cropFace(bmp,face.boundingBox);val q=if(crop!=null)runCatching{embedder?.embed(crop)}.getOrNull()else null;var best:Person?=null;var bestScore=0f;q?.let{query->for(p in people){val s=((cosine(query,p.template)+1f)/2f).coerceIn(0f,1f);if(s>bestScore){bestScore=s;best=p}}};onMatch(true,if(bestScore>=0.70f)best else null,bestScore)}.addOnCompleteListener{proxy.close()}};provider.unbindAll();provider.bindToLifecycle(this,CameraSelector.DEFAULT_FRONT_CAMERA,preview,analysis,capture)}catch(_:Exception){}},ContextCompat.getMainExecutor(this))}
 private fun cropFace(src:Bitmap,box:Rect):Bitmap{val pad=(box.width().coerceAtLeast(box.height())*.35f).toInt();val l=(box.left-pad).coerceIn(0,src.width-1);val t=(box.top-pad).coerceIn(0,src.height-1);val r=(box.right+pad).coerceIn(l+1,src.width);val b=(box.bottom+pad).coerceIn(t+1,src.height);return Bitmap.createBitmap(src,l,t,r-l,b-t)}
 private fun cosine(a:FloatArray,b:FloatArray):Float{if(a.size!=b.size)return -1f;var d=0f;var na=0f;var nb=0f;for(i in a.indices){d+=a[i]*b[i];na+=a[i]*a[i];nb+=b[i]*b[i]};return d/(sqrt(na*nb).coerceAtLeast(1e-8f))}
 private fun submit(kind:String,id:String,score:Float,done:(String)->Unit){if(busy)return;busy=true;val cap=capture?:run{busy=false;done("Camera not ready");return};executor.execute{val file=File.createTempFile("attendance_",".jpg",cacheDir);cap.takePicture(ImageCapture.OutputFileOptions.Builder(file).build(),executor,object:ImageCapture.OnImageSavedCallback{override fun onError(e:ImageCaptureException){busy=false;runOnUiThread{done("Photo capture failed")}};override fun onImageSaved(r:ImageCapture.OutputFileResults){try{val sig=http.newCall(auth(Request.Builder().url("$baseUrl/api/v1/cloudinary/signature").get())).execute().use{x->if(!x.isSuccessful)error("Cloudinary authorization failed");JSONObject(x.body?.string()?:error("Empty signature"))};val upload=MultipartBody.Builder().setType(MultipartBody.FORM).addFormDataPart("file",file.name,file.asRequestBody("image/jpeg".toMediaType())).addFormDataPart("api_key",sig.getString("apiKey")).addFormDataPart("timestamp",sig.getString("timestamp")).addFormDataPart("signature",sig.getString("signature")).addFormDataPart("folder",sig.getString("folder")).build();val cloud=http.newCall(Request.Builder().url("https://api.cloudinary.com/v1_1/${sig.getString("cloudName")}/image/upload").post(upload).build()).execute().use{x->if(!x.isSuccessful)error("Photo upload failed");JSONObject(x.body?.string()?:error("Empty upload"))};val event=JSONObject().put("clientEventId",UUID.randomUUID().toString()).put("employeeId",id).put("status",kind).put("capturedAt",Instant.now().toString()).put("faceMatchScore",score).put("cloudinaryPublicId",cloud.optString("public_id")).put("cloudinaryAssetId",cloud.optString("asset_id")).put("photoSecureUrl",cloud.optString("secure_url"));http.newCall(auth(Request.Builder().url("$baseUrl/api/v1/device/attendance").post(event.toString().toRequestBody("application/json".toMediaType())))).execute().use{x->if(!x.isSuccessful)error(if(x.code==409)"Same status was already recorded recently" else "Attendance submission failed (${x.code})")};file.delete();busy=false;runOnUiThread{done("Attendance recorded: $kind")}}catch(e:Exception){file.delete();busy=false;runOnUiThread{done(e.message?:"Attendance failed")}}}})}}
 private fun auth(b:Request.Builder)=b.header("x-device-token",deviceToken?:"").build()
 private fun yuvToBitmap(p:ImageProxy,rotation:Int):Bitmap{val y=p.planes[0].buffer.duplicate();val u=p.planes[1].buffer.duplicate();val v=p.planes[2].buffer.duplicate();val yb=ByteArray(y.remaining()).also{y.get(it)};val ub=ByteArray(u.remaining()).also{u.get(it)};val vb=ByteArray(v.remaining()).also{v.get(it)};val w=p.width;val h=p.height;val nv=ByteArray(w*h+w*h/2);System.arraycopy(yb,0,nv,0,minOf(yb.size,w*h));var pos=w*h;for(row in 0 until h/2)for(col in 0 until w/2){val ui=row*p.planes[1].rowStride+col*p.planes[1].pixelStride;val vi=row*p.planes[2].rowStride+col*p.planes[2].pixelStride;if(ui<ub.size&&vi<vb.size&&pos+1<nv.size){nv[pos++]=vb[vi];nv[pos++]=ub[ui]}};val out=ByteArrayOutputStream();YuvImage(nv,ImageFormat.NV21,w,h,null).compressToJpeg(Rect(0,0,w,h),82,out);val raw=BitmapFactory.decodeByteArray(out.toByteArray(),0,out.size())?:error("Camera decode failed");if(rotation==0)return raw;return Bitmap.createBitmap(raw,0,0,raw.width,raw.height,Matrix().apply{postRotate(rotation.toFloat())},true)}
}
