import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { Pool } from 'pg';
import { Server } from 'socket.io';
import { createServer } from 'node:http';
import crypto from 'node:crypto';
import { z } from 'zod';
import { adminAuth, signAdmin, verifyPassword } from './auth.js';

const app = express(); const httpServer = createServer(app);
const io = new Server(httpServer, { cors: { origin: '*' } });
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const port = Number(process.env.PORT ?? 8080); const cooldownSeconds = Number(process.env.ATTENDANCE_COOLDOWN_SECONDS ?? 60);
app.use(cors()); app.use(express.json({ limit: '2mb' }));

const loginSchema=z.object({email:z.string().email(),password:z.string().min(1)});
const pairSchema=z.object({pairingCode:z.string().min(4).max(32),deviceName:z.string().max(100).optional(),appVersion:z.string().max(50).optional()});
const attendanceSchema=z.object({clientEventId:z.string().uuid(),employeeId:z.string().uuid(),status:z.enum(['IN','OUT']),capturedAt:z.string().datetime(),faceMatchScore:z.number().min(0).max(1).optional(),cloudinaryPublicId:z.string().max(500).optional(),cloudinaryAssetId:z.string().max(200).optional(),photoSecureUrl:z.string().url().max(2000).optional()});
function hashToken(token:string){return crypto.createHash('sha256').update(token).digest('hex');}

async function deviceAuth(req:express.Request,res:express.Response,next:express.NextFunction){try{const token=req.header('x-device-token');if(!token)return res.status(401).json({error:'DEVICE_TOKEN_REQUIRED'});const r=await pool.query('SELECT id,business_id,status FROM devices WHERE device_token_hash=$1 LIMIT 1',[hashToken(token)]);const d=r.rows[0];if(!d||d.status==='revoked')return res.status(401).json({error:'INVALID_DEVICE'});(req as any).device=d;next();}catch{res.status(500).json({error:'DEVICE_AUTH_FAILED'});}}

app.get('/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'attendance-backend'});}catch{res.status(503).json({ok:false,service:'attendance-backend'});}});

app.post('/api/v1/device/pair',async(req,res)=>{const p=pairSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST'});const r=await pool.query('SELECT id,business_id,name,status FROM devices WHERE pairing_code=$1 AND status<>\'revoked\' LIMIT 1',[p.data.pairingCode.toUpperCase()]);const d=r.rows[0];if(!d)return res.status(404).json({error:'INVALID_OR_EXPIRED_PAIRING_CODE'});const token=crypto.randomBytes(32).toString('base64url');await pool.query(`UPDATE devices SET device_token_hash=$2,pairing_code=NULL,status='online',last_seen_at=now(),app_version=$3,name=COALESCE($4,name) WHERE id=$1`,[d.id,hashToken(token),p.data.appVersion??null,p.data.deviceName??null]);res.json({deviceId:d.id,businessId:d.business_id,deviceName:p.data.deviceName??d.name,deviceToken:token,serverTime:new Date().toISOString()});});

app.post('/api/v1/admin/login',async(req,res)=>{const p=loginSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST'});const r=await pool.query('SELECT id,business_id,email,name,role,password_hash FROM admins WHERE lower(email)=lower($1) AND active=true LIMIT 1',[p.data.email]);const a=r.rows[0];if(!a||!verifyPassword(p.data.password,a.password_hash))return res.status(401).json({error:'INVALID_CREDENTIALS'});const token=signAdmin({id:a.id,businessId:a.business_id,role:a.role});res.json({token,admin:{id:a.id,businessId:a.business_id,email:a.email,name:a.name,role:a.role}});});

app.get('/api/v1/admin/attendance',adminAuth,async(req,res)=>{const a=(req as any).admin;const requested=typeof req.query.businessId==='string'?req.query.businessId:a.businessId;if(requested!==a.businessId)return res.status(403).json({error:'BUSINESS_SCOPE_VIOLATION'});const r=await pool.query(`SELECT a.id,a.status,a.captured_at,a.photo_secure_url,a.cloudinary_public_id,e.employee_code,e.name AS employee_name,d.name AS device_name FROM attendance_events a JOIN employees e ON e.id=a.employee_id JOIN devices d ON d.id=a.device_id WHERE a.business_id=$1 ORDER BY a.captured_at DESC LIMIT 500`,[requested]);res.json({items:r.rows});});
app.get('/api/v1/admin/employees',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query('SELECT id,employee_code,name,department,active,created_at FROM employees WHERE business_id=$1 ORDER BY name',[a.businessId]);res.json({items:r.rows});});
app.get('/api/v1/admin/devices',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query('SELECT id,name,status,app_version,last_seen_at,created_at FROM devices WHERE business_id=$1 ORDER BY name',[a.businessId]);res.json({items:r.rows});});

app.post('/api/v1/device/heartbeat',deviceAuth,async(req,res)=>{const d=(req as any).device;await pool.query(`UPDATE devices SET status='online',last_seen_at=now(),app_version=$2 WHERE id=$1`,[d.id,typeof req.body.appVersion==='string'?req.body.appVersion:null]);io.to(`business:${d.business_id}`).emit('device:status',{deviceId:d.id,status:'online',lastSeenAt:new Date().toISOString()});res.json({ok:true,serverTime:new Date().toISOString()});});

app.post('/api/v1/device/attendance',deviceAuth,async(req,res)=>{const d=(req as any).device;const p=attendanceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST',details:p.error.flatten()});const b=p.data;const client=await pool.connect();try{await client.query('BEGIN');const e=await client.query(`SELECT e.id,e.name FROM employees e JOIN device_employees de ON de.employee_id=e.id WHERE e.id=$1 AND e.business_id=$2 AND e.active=true AND de.device_id=$3`,[b.employeeId,d.business_id,d.id]);if(!e.rowCount){await client.query('ROLLBACK');return res.status(403).json({error:'EMPLOYEE_NOT_ASSIGNED_TO_DEVICE'});}const dup=await client.query('SELECT id FROM attendance_events WHERE device_id=$1 AND client_event_id=$2',[d.id,b.clientEventId]);if(dup.rowCount){await client.query('COMMIT');return res.json({ok:true,duplicate:true,attendanceId:dup.rows[0].id});}const recent=await client.query(`SELECT id,status,captured_at FROM attendance_events WHERE employee_id=$1 AND business_id=$2 AND captured_at > now() - ($3 * interval '1 second') ORDER BY captured_at DESC LIMIT 1`,[b.employeeId,d.business_id,cooldownSeconds]);if(recent.rowCount){await client.query('ROLLBACK');return res.status(409).json({error:'ATTENDANCE_COOLDOWN',lastEvent:recent.rows[0]});}const ins=await client.query(`INSERT INTO attendance_events (business_id,employee_id,device_id,status,captured_at,client_event_id,face_match_score,cloudinary_public_id,cloudinary_asset_id,photo_secure_url) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,server_received_at`,[d.business_id,b.employeeId,d.id,b.status,b.capturedAt,b.clientEventId,b.faceMatchScore??null,b.cloudinaryPublicId??null,b.cloudinaryAssetId??null,b.photoSecureUrl??null]);await client.query('COMMIT');const event={attendanceId:ins.rows[0].id,businessId:d.business_id,deviceId:d.id,employeeId:b.employeeId,employeeName:e.rows[0].name,status:b.status,capturedAt:b.capturedAt};io.to(`business:${d.business_id}`).emit('attendance:new',event);res.status(201).json({ok:true,...event,serverReceivedAt:ins.rows[0].server_received_at});}catch(error){await client.query('ROLLBACK');console.error(error);res.status(500).json({error:'ATTENDANCE_WRITE_FAILED'});}finally{client.release();}});

app.get('/api/v1/cloudinary/signature',deviceAuth,(_req,res)=>{const timestamp=Math.floor(Date.now()/1000);const folder='attendance';const toSign=`folder=${folder}&timestamp=${timestamp}${process.env.CLOUDINARY_API_SECRET}`;const signature=crypto.createHash('sha1').update(toSign).digest('hex');res.json({timestamp,signature,apiKey:process.env.CLOUDINARY_API_KEY,cloudName:process.env.CLOUDINARY_CLOUD_NAME,folder});});
io.on('connection',socket=>{const businessId=socket.handshake.auth?.businessId;if(typeof businessId==='string')socket.join(`business:${businessId}`);});
httpServer.listen(port,()=>console.log(`Attendance backend listening on :${port}`));
