import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { Pool } from 'pg';
import { Server } from 'socket.io';
import { createServer } from 'node:http';
import crypto from 'node:crypto';
import { z } from 'zod';
import { adminAuth, signAdmin, verifyPassword } from './auth.js';

const app=express();
const httpServer=createServer(app);
const io=new Server(httpServer,{cors:{origin:'*'}});
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const port=Number(process.env.PORT??8080);
const cooldownSeconds=Number(process.env.ATTENDANCE_COOLDOWN_SECONDS??60);
app.use(cors()); app.use(express.json({limit:'8mb'}));

const loginSchema=z.object({email:z.string().email(),password:z.string().min(1)});
const pairSchema=z.object({pairingCode:z.string().min(4).max(32),deviceName:z.string().max(100).optional(),appVersion:z.string().max(50).optional()});
const employeeSchema=z.object({employeeCode:z.string().min(1).max(50),name:z.string().min(1).max(150),department:z.string().max(100).optional(),faceTemplate:z.array(z.number().min(-2).max(2)).length(128)});
const faceSchema=z.object({faceTemplate:z.array(z.number().min(-2).max(2)).length(128)});
const assignSchema=z.object({employeeIds:z.array(z.string().uuid())});
const attendanceSchema=z.object({clientEventId:z.string().uuid(),employeeId:z.string().uuid(),status:z.enum(['IN','OUT']),capturedAt:z.string().datetime(),faceMatchScore:z.number().min(0).max(1).optional(),cloudinaryPublicId:z.string().max(500).optional(),cloudinaryAssetId:z.string().max(200).optional(),photoSecureUrl:z.string().url().max(2000).optional()});
function hashToken(t:string){return crypto.createHash('sha256').update(t).digest('hex')}
async function deviceAuth(req:express.Request,res:express.Response,next:express.NextFunction){try{const t=req.header('x-device-token');if(!t)return res.status(401).json({error:'DEVICE_TOKEN_REQUIRED'});const r=await pool.query('SELECT id,business_id,name,status FROM devices WHERE device_token_hash=$1 LIMIT 1',[hashToken(t)]);const d=r.rows[0];if(!d||d.status==='revoked')return res.status(401).json({error:'INVALID_DEVICE'});(req as any).device=d;next()}catch{res.status(500).json({error:'DEVICE_AUTH_FAILED'})}}
app.get('/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'attendance-backend'})}catch{res.status(503).json({ok:false})}});
app.post('/api/v1/device/pair',async(req,res)=>{const p=pairSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST'});const r=await pool.query("SELECT id,business_id,name,status FROM devices WHERE pairing_code=$1 AND status<>'revoked' AND (pairing_expires_at IS NULL OR pairing_expires_at>now()) LIMIT 1",[p.data.pairingCode.trim().toUpperCase()]);const d=r.rows[0];if(!d)return res.status(404).json({error:'INVALID_OR_EXPIRED_PAIRING_CODE'});const token=crypto.randomBytes(32).toString('base64url');await pool.query(`UPDATE devices SET device_token_hash=$2,pairing_code=NULL,pairing_expires_at=NULL,status='online',last_seen_at=now(),app_version=$3,name=COALESCE($4,name) WHERE id=$1`,[d.id,hashToken(token),p.data.appVersion??null,p.data.deviceName??null]);res.json({deviceId:d.id,businessId:d.business_id,deviceName:p.data.deviceName??d.name,deviceToken:token,serverTime:new Date().toISOString()})});
app.post('/api/v1/admin/login',async(req,res)=>{const p=loginSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST'});const r=await pool.query('SELECT id,business_id,email,name,role,password_hash FROM admins WHERE lower(email)=lower($1) AND active=true LIMIT 1',[p.data.email]);const a=r.rows[0];if(!a||!verifyPassword(p.data.password,a.password_hash))return res.status(401).json({error:'INVALID_CREDENTIALS'});res.json({token:signAdmin({id:a.id,businessId:a.business_id,role:a.role}),admin:{id:a.id,businessId:a.business_id,email:a.email,name:a.name,role:a.role}})});
app.get('/api/v1/admin/me',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query(`SELECT ad.id,ad.email,ad.name,ad.role,b.id AS business_id,b.name AS business_name,b.timezone FROM admins ad JOIN businesses b ON b.id=ad.business_id WHERE ad.id=$1`,[a.sub]);if(!r.rowCount)return res.status(404).json({error:'ADMIN_NOT_FOUND'});res.json({admin:r.rows[0]})});
app.get('/api/v1/admin/business',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query('SELECT id,name,timezone,created_at FROM businesses WHERE id=$1',[a.businessId]);if(!r.rowCount)return res.status(404).json({error:'BUSINESS_NOT_FOUND'});res.json({business:r.rows[0]})});
app.get('/api/v1/admin/admins',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query('SELECT id,email,name,role,active,created_at FROM admins WHERE business_id=$1 ORDER BY name',[a.businessId]);res.json({items:r.rows})});
app.get('/api/v1/admin/dashboard',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query(`SELECT (SELECT count(*) FROM employees WHERE business_id=$1 AND active=true)::int staff,(SELECT count(*) FROM devices WHERE business_id=$1 AND status<>'revoked' AND last_seen_at>now()-interval '2 minutes')::int online_devices,(SELECT count(*) FROM attendance_events WHERE business_id=$1 AND captured_at::date=current_date)::int events_today,(SELECT count(DISTINCT employee_id) FROM attendance_events WHERE business_id=$1 AND status='IN' AND captured_at::date=current_date)::int present_today`,[a.businessId]);res.json(r.rows[0])});
app.get('/api/v1/admin/employees',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query('SELECT id,employee_code,name,department,active,created_at,face_model_version,(face_template IS NOT NULL) AS face_enrolled FROM employees WHERE business_id=$1 ORDER BY name',[a.businessId]);res.json({items:r.rows})});
app.post('/api/v1/admin/employees',adminAuth,async(req,res)=>{const a=(req as any).admin;const p=employeeSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'FACE_TEMPLATE_MUST_BE_128_FLOATS'});try{const t=Buffer.from(Float32Array.from(p.data.faceTemplate).buffer);const r=await pool.query(`INSERT INTO employees(business_id,employee_code,name,department,face_template,face_model_version) VALUES($1,$2,$3,$4,$5,'facenet-v1') RETURNING id,employee_code,name,department,active,created_at,(face_template IS NOT NULL) AS face_enrolled`,[a.businessId,p.data.employeeCode.trim(),p.data.name.trim(),p.data.department?.trim()||null,t]);res.status(201).json({employee:r.rows[0]})}catch(e:any){if(e?.code==='23505')return res.status(409).json({error:'EMPLOYEE_CODE_EXISTS'});res.status(500).json({error:'EMPLOYEE_CREATE_FAILED'})}});
app.put('/api/v1/admin/employees/:id/face',adminAuth,async(req,res)=>{const a=(req as any).admin;const p=faceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'FACE_TEMPLATE_MUST_BE_128_FLOATS'});const t=Buffer.from(Float32Array.from(p.data.faceTemplate).buffer);const r=await pool.query(`UPDATE employees SET face_template=$3,face_model_version='facenet-v1' WHERE id=$1 AND business_id=$2 RETURNING id,name,(face_template IS NOT NULL) AS face_enrolled,face_model_version`,[req.params.id,a.businessId,t]);if(!r.rowCount)return res.status(404).json({error:'EMPLOYEE_NOT_FOUND'});res.json({employee:r.rows[0]})});
app.get('/api/v1/admin/devices',adminAuth,async(req,res)=>{const a=(req as any).admin;const r=await pool.query(`SELECT id,name,CASE WHEN status='revoked' THEN 'revoked' WHEN last_seen_at>now()-interval '2 minutes' THEN 'online' ELSE 'offline' END AS status,app_version,last_seen_at,created_at,pairing_code,pairing_expires_at,(SELECT count(*) FROM device_employees de WHERE de.device_id=devices.id)::int AS assigned_employees FROM devices WHERE business_id=$1 ORDER BY name`,[a.businessId]);res.json({items:r.rows})});
app.post('/api/v1/admin/devices',adminAuth,async(req,res)=>{const a=(req as any).admin;const name=typeof req.body?.name==='string'&&req.body.name.trim()?req.body.name.trim():'Attendance Kiosk';let code='';do{code=crypto.randomBytes(4).toString('hex').toUpperCase()}while((await pool.query('SELECT 1 FROM devices WHERE pairing_code=$1',[code])).rowCount);const r=await pool.query("INSERT INTO devices(business_id,name,pairing_code,pairing_expires_at,status) VALUES($1,$2,$3,now()+interval '24 hours','offline') RETURNING id,name,pairing_code,pairing_expires_at,status",[a.businessId,name,code]);res.status(201).json({device:r.rows[0]})});
app.post('/api/v1/admin/devices/:id/regenerate-code',adminAuth,async(req,res)=>{const a=(req as any).admin;let code='';do{code=crypto.randomBytes(4).toString('hex').toUpperCase()}while((await pool.query('SELECT 1 FROM devices WHERE pairing_code=$1',[code])).rowCount);const r=await pool.query("UPDATE devices SET pairing_code=$3,pairing_expires_at=now()+interval '24 hours' WHERE id=$1 AND business_id=$2 AND status<>'revoked' RETURNING id,name,pairing_code,pairing_expires_at",[req.params.id,a.businessId,code]);if(!r.rowCount)return res.status(404).json({error:'DEVICE_NOT_FOUND'});res.json({device:r.rows[0]})});
app.get('/api/v1/admin/devices/:id/assignments',adminAuth,async(req,res)=>{const a=(req as any).admin;const d=await pool.query('SELECT id FROM devices WHERE id=$1 AND business_id=$2',[req.params.id,a.businessId]);if(!d.rowCount)return res.status(404).json({error:'DEVICE_NOT_FOUND'});const r=await pool.query('SELECT employee_id FROM device_employees WHERE device_id=$1 ORDER BY employee_id',[req.params.id]);res.json({employeeIds:r.rows.map(x=>x.employee_id)})});
app.post('/api/v1/admin/devices/:id/assign',adminAuth,async(req,res)=>{const a=(req as any).admin;const p=assignSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST'});const d=await pool.query('SELECT id FROM devices WHERE id=$1 AND business_id=$2',[req.params.id,a.businessId]);if(!d.rowCount)return res.status(404).json({error:'DEVICE_NOT_FOUND'});await pool.query('DELETE FROM device_employees WHERE device_id=$1',[req.params.id]);for(const id of p.data.employeeIds)await pool.query('INSERT INTO device_employees(device_id,employee_id) SELECT $1,id FROM employees WHERE id=$2 AND business_id=$3 ON CONFLICT DO NOTHING',[req.params.id,id,a.businessId]);io.to(`business:${a.businessId}`).emit('device:assignments',{deviceId:req.params.id});res.json({ok:true,employeeIds:p.data.employeeIds})});
app.get('/api/v1/admin/attendance',adminAuth,async(req,res)=>{const a=(req as any).admin;const from=String(req.query.from??'');const to=String(req.query.to??'');const employeeId=String(req.query.employeeId??'');const status=String(req.query.status??'');const deviceId=String(req.query.deviceId??'');const conditions=['ae.business_id=$1'];const params:any[]=[a.businessId];let n=2;if(from){conditions.push(`ae.captured_at >= $${n++}::date`);params.push(from)}if(to){conditions.push(`ae.captured_at < ($${n++}::date + interval '1 day')`);params.push(to)}if(employeeId){conditions.push(`ae.employee_id=$${n++}`);params.push(employeeId)}if(status==='IN'||status==='OUT'){conditions.push(`ae.status=$${n++}`);params.push(status)}if(deviceId){conditions.push(`ae.device_id=$${n++}`);params.push(deviceId)}const r=await pool.query(`SELECT ae.id,ae.employee_id,ae.status,ae.captured_at,ae.photo_secure_url,ae.cloudinary_public_id,ae.cloudinary_asset_id,ae.face_match_score,e.employee_code,e.name AS employee_name,d.name AS device_name FROM attendance_events ae JOIN employees e ON e.id=ae.employee_id JOIN devices d ON d.id=ae.device_id WHERE ${conditions.join(' AND ')} ORDER BY ae.captured_at DESC LIMIT 2000`,params);let events=0,ins=0,outs=0;const days=new Set<string>();const dayPairs=new Map<string,{firstIn?:Date,lastOut?:Date}>();for(const x of r.rows){events++;if(x.status==='IN')ins++;else outs++;const day=new Date(x.captured_at).toISOString().slice(0,10);days.add(`${x.employee_id}:${day}`);const key=`${x.employee_id}:${day}`;const p=dayPairs.get(key)??{};if(x.status==='IN'&&(!p.firstIn||new Date(x.captured_at)<p.firstIn))p.firstIn=new Date(x.captured_at);if(x.status==='OUT'&&(!p.lastOut||new Date(x.captured_at)>p.lastOut))p.lastOut=new Date(x.captured_at);dayPairs.set(key,p)}let minutes=0;for(const p of dayPairs.values())if(p.firstIn&&p.lastOut&&p.lastOut>p.firstIn)minutes+=Math.floor((p.lastOut.getTime()-p.firstIn.getTime())/60000);let presentDays=days.size;let absentDays=0;if(employeeId&&from&&to){const start=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);const total=Math.max(0,Math.floor((end.getTime()-start.getTime())/86400000)+1);absentDays=Math.max(0,total-presentDays)}res.json({items:r.rows,summary:{events,ins,outs,presentDays,absentDays,hours:`${Math.floor(minutes/60)}h ${minutes%60}m`},filters:{from:from||null,to:to||null,employeeId:employeeId||null,status:status||null,deviceId:deviceId||null}})});
app.get('/api/v1/device/manifest',deviceAuth,async(req,res)=>{const d=(req as any).device;const r=await pool.query(`SELECT e.id,e.employee_code,e.name,encode(e.face_template,'base64') AS encoded_template,e.face_model_version FROM employees e JOIN device_employees de ON de.employee_id=e.id WHERE de.device_id=$1 AND e.business_id=$2 AND e.active=true ORDER BY e.name`,[d.id,d.business_id]);res.json({businessId:d.business_id,deviceId:d.id,employees:r.rows.map((e:any)=>{let faceTemplate:null|number[]=null;if(e.encoded_template){const b=Buffer.from(e.encoded_template,'base64');faceTemplate=Array.from(new Float32Array(b.buffer,b.byteOffset,Math.floor(b.length/4)))}return{id:e.id,employeeCode:e.employee_code,name:e.name,faceTemplate,faceModelVersion:e.face_model_version}})})});
app.post('/api/v1/device/heartbeat',deviceAuth,async(req,res)=>{const d=(req as any).device;await pool.query(`UPDATE devices SET status='online',last_seen_at=now(),app_version=$2 WHERE id=$1`,[d.id,typeof req.body.appVersion==='string'?req.body.appVersion:null]);io.to(`business:${d.business_id}`).emit('device:status',{deviceId:d.id,status:'online',lastSeenAt:new Date().toISOString()});res.json({ok:true,serverTime:new Date().toISOString()})});
app.post('/api/v1/device/attendance',deviceAuth,async(req,res)=>{const d=(req as any).device;const p=attendanceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_REQUEST'});const b=p.data;const c=await pool.connect();try{await c.query('BEGIN');const e=await c.query(`SELECT e.id,e.name FROM employees e JOIN device_employees de ON de.employee_id=e.id WHERE e.id=$1 AND e.business_id=$2 AND e.active=true AND de.device_id=$3`,[b.employeeId,d.business_id,d.id]);if(!e.rowCount){await c.query('ROLLBACK');return res.status(403).json({error:'EMPLOYEE_NOT_ASSIGNED_TO_DEVICE'})}const dup=await c.query('SELECT id FROM attendance_events WHERE device_id=$1 AND client_event_id=$2',[d.id,b.clientEventId]);if(dup.rowCount){await c.query('COMMIT');return res.json({ok:true,duplicate:true,attendanceId:dup.rows[0].id})}const recent=await c.query(`SELECT id,status,captured_at FROM attendance_events WHERE employee_id=$1 AND business_id=$2 AND status=$3 AND captured_at > now() - ($4 * interval '1 second') ORDER BY captured_at DESC LIMIT 1`,[b.employeeId,d.business_id,b.status,cooldownSeconds]);if(recent.rowCount){await c.query('ROLLBACK');return res.status(409).json({error:'ATTENDANCE_COOLDOWN',lastEvent:recent.rows[0]})}const ins=await c.query(`INSERT INTO attendance_events (business_id,employee_id,device_id,status,captured_at,client_event_id,face_match_score,cloudinary_public_id,cloudinary_asset_id,photo_secure_url) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,server_received_at`,[d.business_id,b.employeeId,d.id,b.status,b.capturedAt,b.clientEventId,b.faceMatchScore??null,b.cloudinaryPublicId??null,b.cloudinaryAssetId??null,b.photoSecureUrl??null]);await c.query('COMMIT');const event={attendanceId:ins.rows[0].id,businessId:d.business_id,deviceId:d.id,employeeId:b.employeeId,employeeName:e.rows[0].name,status:b.status,capturedAt:b.capturedAt};io.to(`business:${d.business_id}`).emit('attendance:new',event);res.status(201).json({ok:true,...event,serverReceivedAt:ins.rows[0].server_received_at})}catch(err){await c.query('ROLLBACK');console.error(err);res.status(500).json({error:'ATTENDANCE_WRITE_FAILED'})}finally{c.release()}});
app.get('/api/v1/cloudinary/signature',deviceAuth,(_req,res)=>{const timestamp=Math.floor(Date.now()/1000);const folder='attendance';const signature=crypto.createHash('sha1').update(`folder=${folder}&timestamp=${timestamp}${process.env.CLOUDINARY_API_SECRET}`).digest('hex');res.json({timestamp,signature,apiKey:process.env.CLOUDINARY_API_KEY,cloudName:process.env.CLOUDINARY_CLOUD_NAME,folder})});
io.on('connection',socket=>{const businessId=socket.handshake.auth?.businessId;if(typeof businessId==='string')socket.join(`business:${businessId}`)});
async function boot(){await pool.query("ALTER TABLE devices ADD COLUMN IF NOT EXISTS pairing_expires_at TIMESTAMPTZ");httpServer.listen(port,'0.0.0.0',()=>console.log(`Attendance backend listening on :${port}`))}
boot().catch(err=>{console.error('Backend boot failed',err);process.exit(1)});
